# Quarkus will choose application.yaml over application.properties.
quarkus:
    http:
        port: 8080
        read-timeout: 30m
        limits:
          max-body-size: 500M

    package:
        uber-jar: true

    # Logging (disable console on prod)
    log:
        level: INFO
        category:
            "org.commonjava.service.storage":
                level: DEBUG
        console:
            level: DEBUG
            enable: true
        file:
            enable: true
            path: "log/pathmap.log"
            level: DEBUG
            format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
            rotation:
                max-backup-index: 5
                max-file-size: 10M

    swagger-ui:
        always-include: true

#honeycomb:
#    enabled: false
#    dataset: test
#    write-key: 61c935e7d6f5ef5b992fe142deb2569c
#    base-sample-rate: 50

cassandra:
    host: localhost
    port: 9042
    user: cassandra
    pass: cassandra
    keyspace: indystorage

storage:
    baseDir: "/tmp"
    readonly: false

#kafka:
#    bootstrap:
#        servers: "localhost:9092"

"%dev":
    quarkus:
        kubernetes-config:
            enabled: false
        log:
            level: INFO
            category:
                "org.commonjava.service.storage":
                    level: TRACE
            console:
                enable: true
            file:
                enable: true
                path: "/tmp/pathmap-storage-service.log"
                format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
                rotation:
                    max-backup-index: 5
                    max-file-size: 10M

    cassandra:
        host: localhost
        port: 9042
        user: cassandra
        pass: cassandra
        keyspace: indystorage

#    kafka:
#        bootstrap:
#            servers: "localhost:9092"
#
#    # Configuring the incoming/outgoing channel
#    mp:
#        messaging:
#            outgoing:
#                file-event-out:
#                    connector: smallrye-kafka
#                    topic: file-event
#                    value:
#                        serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#            incoming:
#                file-event-in:
#                    connector: smallrye-kafka
#                    topic: file-event
#                    value:
#                        deserializer: org.commonjava.service.storage.event.FileEventDeserializer

