# Quarkus will choose application.yaml over application.properties.
quarkus:
    http:
        port: 8080
        read-timeout: 30m
        limits:
          max-body-size: 500M
    package:
        uber-jar: true
    oidc:
        enabled: true
        auth-server-url: "https://localhost:8543/realms/indyreposervice"
        client-id: indy
        credentials:
            secret: secret
        tls:
            verification: none
        token:
            issuer: any
    security:
        auth:
            enabled-in-dev-mode: false
    # Logging (disable console on prod)
    log:
        level: INFO
        category:
            "org.commonjava.service.storage":
                level: DEBUG
        console:
            level: DEBUG
            enable: true
        file:
            enable: true
            path: "log/pathmap.log"
            level: DEBUG
            format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
            rotation:
                max-backup-index: 5
                max-file-size: 10M

    swagger-ui:
        always-include: true

cassandra:
    host: localhost
    port: 9042
    user: cassandra
    pass: cassandra
    keyspace: indystorage

storage:
    baseDir: "/tmp"
    readonly: false

"%dev":
    quarkus:
        kubernetes-config:
            enabled: false
        log:
            level: INFO
            category:
                "org.commonjava.service.storage":
                    level: DEBUG
            console:
                enable: true
            file:
                enable: true
                path: "/tmp/pathmap-storage-service.log"
                format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
                rotation:
                    max-backup-index: 5
                    max-file-size: 10M

    cassandra:
        host: localhost
        port: 9042
        user: cassandra
        pass: cassandra
        keyspace: indystorage
